
# - name: get and unzip prometheus
#   shell: |
#     wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
#     tar xvfz prometheus-2.19.0.linux-amd64.tar.gz
#     cd prometheus-2.19.0.linux-amd64
#     ./prometheus --config.file=./prometheus.yml

- name: create dir to host prometheus config and data
  become: yes
  shell: |
    useradd --no-create-home prometheus
    mkdir /etc/prometheus
    mkdir /var/lib/prometheus

- name: get and unzip prometheus
  shell: |
    wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    tar xvfz prometheus-2.19.0.linux-amd64.tar.gz

- name: install prometheus
  become: yes
  shell: |
    cp prometheus-2.19.0.linux-amd64/prometheus /usr/local/bin
    cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
    cp -r prometheus-2.19.0.linux-amd64/consoles /etc/prometheus
    cp -r prometheus-2.19.0.linux-amd64/console_libraries /etc/prometheus
    cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
    rm -rf prometheus-2.19.0.linux-amd64.tar.gz prometheus-2.19.0.linux-amd64

- name: configure prometheus
  become: yes
  template:
    src: "files/prometheus.yml"
    dest: "/etc/prometheus/prometheus.yml"   

- name: configure prometheus as service
  become: yes
  template:
    src: "files/prometheus.service"
    dest: "/etc/systemd/system/prometheus.service"

- name: change permissions
  become: yes
  shell: |
    chown prometheus:prometheus /etc/prometheus
    chown prometheus:prometheus /usr/local/bin/prometheus
    chown prometheus:prometheus /usr/local/bin/promtool
    chown -R prometheus:prometheus /etc/prometheus/consoles
    chown -R prometheus:prometheus /etc/prometheus/console_libraries
    chown -R prometheus:prometheus /var/lib/prometheus
    chown prometheus:prometheus /etc/prometheus/prometheus.yml

- name: configure systemd to start prometheus on boot
  become: yes
  shell: |
    systemctl daemon-reload
    systemctl enable prometheus
    systemctl start prometheus