- name: Exercise for setting up a web server in an EC2
  hosts: all
  user: ubuntu
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: {$TYPEORM_CONNECTION}
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: {$TYPEORM_HOST}
    TYPEORM_PORT: {$TYPEORM_PORT}
    TYPEORM_USERNAME: {$TYPEORM_USERNAME}
    TYPEORM_PASSWORD: {$TYPEORM_PASSWORD}
    TYPEORM_DATABASE: {$TYPEORM_DATABASE}
  roles:
  - configure-server
  # - configure-prometheus-node-exporter