- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/app
    state: directory

- name:
  become: yes
  shell: |
    apt install -y rsync

- name: copy ditribution folder to remote server
  become: yes
  synchronize:
    src: dist
    dest: ~/app
  register: copy_output
    
- debug: var=copy_output


