- name: install alerts manager
  become: yes
  shell: |
    wget https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    tar xvfz alertmanager-0.21.0.linux-amd64.tar.gz
    cp alertmanager-0.21.0.linux-amd64/alertmanager /usr/local/bin
    cp alertmanager-0.21.0.linux-amd64/amtool /usr/local/bin/
    mkdir /var/lib/alertmanager
    rm -rf alertmanager*


- name: configure alertmanager
  become: yes
  template:
    src: "files/alertmanager.yml"
    dest: "/etc/prometheus/alertmanager.yml"  

- name: configure alertmanager as service
  become: yes
  template:
    src: "files/alertmanager.service"
    dest: "/etc/systemd/system/alertmanager.service"  

- name: configure systemd to start alertmanager on boot
  become: yes
  shell: |
    systemctl daemon-reload
    systemctl enable alertmanager
    systemctl start alertmanager  


- name: setup alert rules
  become: yes
  template:
    src: "files/rules.yml"
    dest: "/etc/prometheus/rules.yml"  
  
- name: change permissions
  become: yes
  shell: | 
    chown -R prometheus:prometheus /etc/prometheus
    chown -R prometheus:prometheus /var/lib/alertmanager

- name: copy in alert config
  become: yes
  template:
    src: "files/alert_part.yml"
    dest: "./"


- name: add alerting to prometheus config
  become: yes
  shell: |
    sed -i '5r alert_part.yml' /etc/prometheus/prometheus.yml
    systemctl restart prometheus