version: 2.1

jobs:
# =========================================================================================================
# BUILD
  backend_build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - back-end
  
      - run:
          name: Build backend
          command: |
            cd backend
            npm i
            npm run build
          
      - save_cache:
          paths:
            - backend/node_modules 
          key: back-end

  frontend_build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - front-end

      - run:
          name: Build frontend
          command: |
            cd frontend
            npm i
            npm run build
          
      - save_cache:
          paths:
            - frontend/node_modules
          key: front-end
  
# =======================================================================================================
# TEST
  backend_tests:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - back-end
     
      - run:
          name: Run tests with JUnit as reporter
          command: |
            cd backend
            npm i
            npm add --dev jest-junit
            npm run test --reporters=jest-junit
     
      - store_test_results:
          path: backend/test-results
      - store_artifacts:
          path: backend/test-results/junit/junit.xml
    
            
      - save_cache:
          paths:
            - backend/node_modules 
          key: back-end

  frontend_tests:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - front-end

      - run:
          name: Run tests with JUnit as reporter
          command: |
            cd frontend
            npm i
            npm add --dev jest-junit
            npm run test --reporters=jest-junit
        
      - store_test_results:
          path: frontend/test-results
      - store_artifacts:
          path: frontend/test-results/junit/junit.xml
          
      - save_cache:
          paths:
            - frontend/node_modules  
          key: front-end
# =========================================================================================================
# ANALYZE
  audit-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - back-end
      - run:
          name: Scan backend dependencies
          command: |
            cd backend
            npm i
            npm audit --audit-level=critical


  audit-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - front-end
      - run:
          name: Scan frontend dependencies
          command: |
            cd frontend
            npm i
            npm audit --audit-level=critical



workflows:
  default:
    jobs:
      - backend_build
      - frontend_build
      
      - backend_tests:
          requires: 
            - backend_build
      - frontend_tests:
          requires: 
            - frontend_build

      - audit-backend:
          requires:
            - backend_tests
      - audit-frontend:
          requires:
            - frontend_tests
      



             

