version: 2.1

jobs:
  backend_build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - backend-dep-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - backend-dep-v2-{{ .Branch }}-
            - backend-dep-v2-
  
      - run:
          name: Build backend
          command: |
            cd backend
            npm i
            npm run build
          
      - save_cache:
          paths:
            - backend/node_modules  # location depends on npm version
          key: backend-dep-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}


  backend_tests:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - backend-dep-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - backend-dep-v2-{{ .Branch }}-
            - backend-dep-v2-
     
      - run:
          name: Run tests with JUnit as reporter
          command: |
            cd backend
            npm i
            yarn add --dev jest-junit
            yarn test --ci --runInBand --reporters=default --reporters=jest-junit
     
      - store_test_results:
          path: backend/test-results
      - store_artifacts:
          path: backend/test-results/junit/junit.xml
    
            
      - save_cache:
          paths:
            - backend/node_modules  # location depends on npm version
          key: backend-dep-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}

  frontend_build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - frontend-dep-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - frontend-dep-v2-{{ .Branch }}-
            - frontend-dep-v2-

      - run:
          name: Build frontend
          command: |
            cd frontend
            npm i
            npm run build
          
      - save_cache:
          paths:
            - frontend/node_modules  # location depends on npm version
          key: frontend-dep-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
  


  frontend_tests:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - frontend-dep-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - frontend-dep-v2-{{ .Branch }}-
            - frontend-dep-v2-

      - run:
          name: Run tests with JUnit as reporter
          command: |
            cd frontend
            npm i
            yarn add --dev jest-junit
            yarn test --ci --runInBand --reporters=default --reporters=jest-junit
        
      - store_test_results:
          path: frontend/test-results
      - store_artifacts:
          path: frontend/test-results/junit/junit.xml
          
      - save_cache:
          paths:
            - frontend/node_modules  # location depends on npm version
          key: frontend-dep-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
        

workflows:
  default:
    jobs:
      - backend_build
      - frontend_build
      - backend_tests:
          requires: 
            - backend_build
      - frontend_tests:
          requires: 
            - frontend_build

