version: 2.1

jobs:
  backend_build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - back-end
  
      - run:
          name: Build backend
          command: |
            cd backend
            npm i
            npm run build
          
      - save_cache:
          paths:
            - backend/node_modules  # location depends on npm version
          key: back-end


  backend_tests:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       # when lock file changes, use increasingly general patterns to restore cache
      #       - back-end
     
      - run:
          name: Run tests with JUnit as reporter
          command: |
            cd backend
            npm i
            npm add --dev jest-junit
            npm run test --reporters=jest-junit
     
      - store_test_results:
          path: backend/test-results
      - store_artifacts:
          path: backend/test-results/junit/junit.xml
    
            
      # - save_cache:
      #     paths:
      #       - backend/node_modules  # location depends on npm version
      #     key: back-end

  frontend_build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - front-end

      - run:
          name: Build frontend
          command: |
            cd frontend
            npm i
            npm run build
          
      - save_cache:
          paths:
            - frontend/node_modules  # location depends on npm version
          key: front-end
  


  frontend_tests:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - front-end

      - run:
          name: Run tests with JUnit as reporter
          command: |
            cd frontend
            npm i
            npm add --dev jest-junit
            npm run test --reporters=jest-junit
        
      - store_test_results:
          path: frontend/test-results
      - store_artifacts:
          path: frontend/test-results/junit/junit.xml
          
      - save_cache:
          paths:
            - frontend/node_modules  # location depends on npm version
          key: front-end
        

workflows:
  default:
    jobs:
      - backend_build
      - frontend_build
      - backend_tests:
          requires: 
            - backend_build
      - frontend_tests:
          requires: 
            - frontend_build

